name: earth_observation_cfep
channels:
  - defaults
dependencies:
  - autopep8=1.6.0
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - openssl=1.1.1o
  - pip=21.2.4
  - pycodestyle=2.8.0
  - python=3.7.13
  - setuptools=61.2.0
  - sqlite=3.38.3
  - toml=0.10.2
  - wheel=0.37.1
  - pip:
branca==0.5.0
colorcet==3.0.0
earthengine-api==0.1.315
geemap==0.14.0
geetools==0.6.14
matplotlib==3.5.2
numpy==1.21.6
pandas==1.3.5
Pillow==9.1.1
plotly==5.8.2
python-dateutil==2.8.2
scipy==1.7.3
streamlit==1.10.0
streamlit-folium==0.6.13