name: earth_observation_cfep
channels:
  - defaults
dependencies:
  - autopep8
  - ca-certificates
  - certifi
  - openssl
  - pip
  - pycodestyle
  - python
  - setuptools
  - sqlite
  - toml
  - wheel
  - pip:
    - altair
    - anyio
    - argon2-cffi
    - argon2-cffi-bindings
    - attrs
    - babel
    - backcall
    - backports-zoneinfo
    - beautifulsoup4
    - bleach
    - blinker
    - bqplot
    - branca
    - cachetools
    - cffi
    - charset-normalizer
    - colorama
    - colorcet
    - colour
    - commonmark
    - cycler
    - debugpy
    - decorator
    - defusedxml
    - earthengine-api
    - ee-extra
    - entrypoints
    - fastjsonschema
    - ffmpeg-python
    - filelock
    - folium
    - fonttools
    - future
    - gdown
    - geeadd
    - geemap
    - geetools
    - geocoder
    - geojson
    - gitdb
    - gitpython
    - google-api-core
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-cloud-core
    - google-cloud-storage
    - google-crc32c
    - google-resumable-media
    - googleapis-common-protos
    - httplib2
    - httplib2shim
    - idna
    - importlib-metadata
    - importlib-resources
    - ipyevents
    - ipyfilechooser
    - ipykernel
    - ipyleaflet
    - ipython
    - ipython-genutils
    - ipytree
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - kiwisolver
    - logzero
    - mapclassify
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - notebook-shim
    - numpy
    - packaging
    - pandas
    - pandocfilters
    - param
    - parso
    - pickleshare
    - pillow
    - plotly
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - pyarrow
    - pyasn1
    - pyasn1-modules
    - pycparser
    - pycrs
    - pyct
    - pydeck
    - pygments
    - pympler
    - pyparsing
    - pyrsistent
    - pyshp
    - pysocks
    - python-box
    - python-dateutil
    - pytz
    - pytz-deprecation-shim
    - pywin32
    - pywinpty
    - pyzmq
    - ratelim
    - requests
    - rich
    - rsa
    - sankee
    - scikit-learn
    - scipy
    - send2trash
    - six
    - smmap
    - sniffio
    - soupsieve
    - streamlit
    - streamlit-folium
    - tenacity
    - terminado
    - threadpoolctl
    - tinycss2
    - toolz
    - tornado
    - tqdm
    - traitlets
    - traittypes
    - typing-extensions
    - tzdata
    - tzlocal
    - uritemplate
    - urllib3
    - validators
    - watchdog
    - wcwidth
    - webencodings
    - whitebox
    - whiteboxgui
    - widgetsnbextension
    - xyzservices
    - zipp
