[earth_observation_cfep]
type = "service_account"
project_id = "ee-mazy"
private_key_id = "669406f2a87dd9a42a503633f17c4d350c677672"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCl8qDbqySTDWkY
m24kIEcJHvqEoLEVpVkEuwdHL3C6B59ZJ2N/2w5m0CiuPGp1HYP+Yfz+RthxcD9D
# ... (rest of your private key) ...
-----END PRIVATE KEY-----
"""
client_email = "cep-eo@ee-mazy.iam.gserviceaccount.com"
client_id = "113814363165436237041"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/cep-eo%40ee-mazy.iam.gserviceaccount.com"
